# Generated by Django 3.2.22 on 2023-11-03 19:41

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='featured_image_alt',
            field=models.CharField(default='placeholder', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=djrichtextfield.models.RichTextField(max_length=1000),
        ),
    ]
