# Generated by Django 3.2.22 on 2023-11-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20231103_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='featured_image_alt',
            field=models.CharField(default='', max_length=100),
        ),
    ]
