# Generated by Django 3.2.22 on 2023-11-14 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_rename_for_serving_recipe_additional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='additional',
        ),
    ]
