# Generated by Django 3.2.22 on 2023-11-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='serving',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.IntegerField(),
        ),
    ]
