# Generated by Django 3.2.22 on 2023-11-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20231115_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='serving',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
